title: 阿科博客
email: Arctos@163.com
brief-intro: 阿科的博客 开发爱好者
description_footer: 人生旅途美景

github_username: wonkerr
duoshuo_shortname: wonkerr

url: http://wonkerr.github.io
permalink: /:year/:month-:day/:title

highlighter: pygments
markdown: kramdown
pygments: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

category_dir: category/
tag_dir: tag/
base-url: ""

excerpt_separator: "\n\n\n\n"

gems: [jekyll-paginate]
paginate: 8
