title: 博客
email: Arctos@163.com
description: 阿科的博客 开发爱好者

github_username:  wonkerr

url: http://wonkerr.github.io
permalink: /:title

highlighter: pygments
markdown: kramdown
pygments: true
paginate: 8

